# dumps the changelog from last saved tag-version till now (HEAD)
./release.php changelog 

# Take the time to review docs/CHANGELOG and write up a nice human 
# readable docs/NOTES

# Build a new version.
./release.php bake v0.9.3-beta
# You get 5s to hit CTRL+C if you didn't make the NOTES list 
